# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Site settings
title: Nate Haris
subtitle: nateharis@gmail.com
email: nateharis@gmail.com
description: > 
  Personal Portfolio showcasing some of my engineering and design projects. Updated over time as projects progress.
baseurl: "" # Leave empty for username.github.io
url: "https://nh428.github.io" # Your site URL

# User settings
username: Nate Haris
user_description: Electrical Engineer | Software Designer | Computer Arichitect
user_title: Nate Haris

# Social media links (optional)
github_username: nh428
linkedin_username: nh428
