#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Custom Dashboard PCB', url: 'proj-1', image: 'assets/img/projects/proj-1/thumbnail.png'}
- {name: 'RSC-V Multi-Core Processor',   url: 'proj-3'}
- {name: 'Battery Management System Test PCB', url: 'proj-2'}
- {name: 'API Endpoint Vulnerability Research',  url: 'proj-4'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/nh428'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/nh428'}
- {icon: 'envelope',  link: 'mailto:mailto:nh428@cornell.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
